# Generated by Django 5.2.5 on 2025-09-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='lname',
            field=models.CharField(default='F', max_length=100),
            preserve_default=False,
        ),
    ]
