# Generated by Django 5.2.5 on 2025-09-06 14:03

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFolio', '0002_rename_name_personalinfo_fname_personalinfo_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_photo',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profile_photos/'),
        ),
    ]
