# Generated by Django 5.2.5 on 2025-09-22 09:24

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFolio', '0004_project_demo_link_project_end_date_project_highlight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='project_images'),
        ),
    ]
